### ISSUE TITLE
apiVersion depricated

### ISSUE THREAD

**Issue by th1j5** [sagemathinc/cocalc-kubernetes#14]
Is it possible that
`apiVersion: extensions/v1beta1`
is deprecated in favor of
`apiVersion: apps/v1`?
If that's the case, this should be updated in deployment.yaml
Sources:
[other github issue](https://github.com/coreos/etcd-operator/issues/2126#issuecomment-539927430)
and [blogpost](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
Warning: I've no Kubernetes knowledge whatshowever, I was just curious if this is going to install (and the deprecated option didn't work).
Using some kubernetes called: https://k3s.io/

**Comment by williamstein** [comment]
That makes sense.  I created a lot of these yaml files (the ones behind the scenes for https://cocalc.com) long long ago, since we were pretty early heavy users of Kubernetes...
