### ISSUE TITLE
how to increase the memory and core quota per project?

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-kubernetes#6]
Hi, 
I just successfully deployed the cocalc on OKD/openshift, 
are there easy way to tune the core and ram quota per project??

**Comment by williamstein** [comment]
Try this:
1. Make one of your users an admin as explained at https://github.com/sagemathinc/cocalc-docker#make-a-user-an-admin
2. Open project settings for any project, then click "Admin Edit..." and edit the quota for that project.  The core and ram quota might work.  I don't know. Looking at the source code it looks like there's some hope.

**Comment by arm2arm** [comment]
Nice It works...
What is the member hosting?:)
are there way to set the default quota for the projects?

**Comment by williamstein** [comment]
> What is the member hosting?:)

If set, it just means that a certain label will be set on the project pod.  That likely currently has no impact in practice right now, but could be implemented at some later stage.  Here's the relevant code that is run to create the yaml file for the project pod:

https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/smc_compute.py#L616

> are there way to set the default quota for the projects?

No, but you clan become an admin and adjust quotas for specific projects in project settings.

That said, I know that @haraldschilly implemented something in Admin site settings for changing the defaults, but I don't know where or when it will be released (probably soon). 

Many thanks for testing out cocalc-kubernetes and asking questions. You're probably the first person in the world to seriously use/test it, and I really appreciate it.

**Comment by arm2arm** [comment]
I got this monster:OKD 3.11 running on our OVIRT enviroment, if you are interested I can add my notes how to deploy cocalc with openshift.
I wish to deploy kubernetes version in our production system. currently we are on the docker :(

**Comment by williamstein** [comment]
>  if you are interested I can add my notes how to deploy cocalc with openshift.

Yes, definitely.  E.g., if you could make a PR and just add a whole new markdown file with your steps, that would be greatly appreciated and beneficial to the community.  Thanks!

**Comment by arm2arm** [comment]
need to find a way to add a storage, still trying..

**Comment by RooseveltAdvisors** [comment]
@williamstein Thanks for making Cocalc available for free. Appreciate it. I'm testing it out on my Kubernetes cluster as well. But I don't see the quota settings in the admin console.   

I have already made myself the admin

```bash
root@cocalc-kubernetes-server-5b55cd4c56-k8tpw:/# make-user-admin yuan@intellinum.co
UPDATE 1
``` 

![image](https://user-images.githubusercontent.com/4559435/88977315-4f3a7000-d283-11ea-9f23-44a35e2024f7.png)

**Comment by williamstein** [comment]
>  I'm testing it out on my Kubernetes cluster as well. But I don't see the quota settings in the admin console.

I'm not sure to what extent this will help, but try (1) making yourself an admin and in the Admin page under site settings set "KuCalc UI" to true, then (2) refresh your browser.

**Comment by RooseveltAdvisors** [comment]
Thanks,William. You're the man!!!

It worked after I changed the `KuCalc UI` setting from `no` to `on-prem` and hit the save button down below.

I'm posting my screenshots here for anyone that might run into the same problem.

![KuCalc UI setting](https://user-images.githubusercontent.com/4559435/88980638-c541d580-d289-11ea-9cdf-39027cfe790f.gif)

**Comment by williamstein** [comment]
I don't know to what extent the quotas will actually have an impact on the pod that gets created in Kubernetes.  E.g., the disk quota won't do anything.
